am62x_var_som: Define efi_add_known_memory finction in board am62x_var_som.c file
When DRAM size is 512 MiB, to prevent U-Boot memory area from overlapping with
required reserved memory areas, RESERVED_MEMORY is excluded from RAM top value,
but in this case below issue occurs:

ERROR: reserving fdt memory region failed (addr=9c800000 size=300000 flags=4)
ERROR: reserving fdt memory region failed (addr=9cb00000 size=100000 flags=4)
ERROR: reserving fdt memory region failed (addr=9cc00000 size=e00000 flags=4)
ERROR: reserving fdt memory region failed (addr=9da00000 size=100000 flags=4)
ERROR: reserving fdt memory region failed (addr=9db00000 size=c00000 flags=4)
ERROR: reserving fdt memory region failed (addr=9e780000 size=80000 flags=4)
ERROR: reserving fdt memory region failed (addr=9e800000 size=1800000 flags=4)
   Loading Device Tree to 000000008feed000, end 000000008fffffff ... OK
Working FDT set to 8feed000

Starting kernel ...

This occurs because when reserving EFI subsystem memory, this RESERVED_MEMORY parameter
is not taken into account and will also be reserved.

To change this behavior, overwrite the weak function in the board file, keeping it original,
just fix the missing DRAM bank size check and exclude RESERVED_MEMORY from the reservation
when DRAM size is 512 MB.