fdt_support: Replace IS_ENABLED(CONFIG_VIDEO) with CONFIG_IS_ENABLED(VIDEO)
The global_data structure members video_top and video bottom are
added in global_data in condition if CONFIG_IS_ENABLED(VIDEO),
which in SPL BUILD checks if CONFIG_SPL_VIDEO is enabled.
But the function fdt_add_fb_mem_rsv is defined in condition
if IS_ENABLED(CONFIG_VIDEO), which does not check whether video
support is enabled in the SPL stage, so this leads to the compilation error:
fdt_support.c:1982:15: error: 'gd_t' {aka 'volatile struct global_data'} has no member named 'video_bottom'

Replace IS_ENABLED(CONFIG_VIDEO) with CONFIG_IS_ENABLED(VIDEO),
to use the condition that will distinctly control the video support
enabled in SPL and 'U-Boot proper' builds

Signed-off-by: Natalia Kovalenko <natasha.k@variscite.com>